# baseURL: "https://rchhibber.github.io/" 
baseURL: "https://rachhi.github.io/" #name of GitHub repository
# url: "https://rachhi.github.io" #custom url to be used instead of GitHub repository

title: Raveena Chhibber | NSF Gradute Fellow | UW 
theme: PaperMod
pagination:
  pagerSize: 40

taxonomies:
    tag: tags

menu:
    main:
        # - name: Book
        #   url: /18/
        #   weight: 1
        - name: Papers
          url: /papers/
          weight: 2
        - name: Dashboard
          url: /dashboard/
          weight: 3
        # - name: Courses
        #   url: /courses/
        #   weight: 4
        # - name: Design
        #   url: /design/
        #   weight: 5        

params:
    description: "Raveena Chhibber | NSF Gradute Fellow"
    author: Raveena Chhibber
    # googleAnalyticsID: "G-97G4MZ4061"
    images: ["cover.png"]
    DateFormat: "January 2026"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    ShowWordCount: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    disableScrollToTop: true
    ShowCodeCopyButtons: true
    ShowToc: false
    TocOpen: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Raveena Chhibber | NSF Graduate Fellow
          subtitle: "I am a graduate student in the Neurosciene Program at University of Washington, Seattle. Broadly, I am interested in motor control and neuromechanics. Currently, I am an NSF GRFP Fellow working with John Tuthill and Bing Brunton."
          imageUrl: "/picture.jpeg"
          imageWidth: 130
          imageHeight: 130
          buttons:
            # - name: Book
            #   url: /18/
            - name: Papers
              url: /papers/
            - name: Projects
              url: /dashboard/  
            # - name: Courses
            #   url: /courses/
            # - name: Design
            #   url: /design/

    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:rchhib@uw.edu
        # - name: Location
        #   url: /location/
        # - name: Office Hours
        #   url: /officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=TEgzSrkAAAAJ&hl=en
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/rachhi

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Raveena Chhibber"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

enableInlineShortcodes: true
enableRobotsTXT: true
titleCaseStyle: 'none'
enableGitInfo: true
buildFuture: true